### ISSUE TITLE
Type Error when trying to login

### ISSUE THREAD

**Issue by amitkhairnar44** [kfiross/flutter_facebook_login_web#1]
Here's the error log when i tried to login using: 
 ```dart
final FacebookLoginResult result = await facebookSignIn.logIn(['email']);
```

```
Error: Expected a value of type 'Map<String, dynamic>', but got one of type 'LinkedMap<dynamic, dynamic>'
    at Object.throw_ [as throw] (http://localhost:60059/dart_sdk.js:4322:11)
    at Object.castError (http://localhost:60059/dart_sdk.js:4293:15)
    at Object.cast [as as] (http://localhost:60059/dart_sdk.js:4609:17)
    at dart.LegacyType.new.as (http://localhost:60059/dart_sdk.js:6151:60)
    at logIn (http://localhost:60059/packages/flutter_facebook_login_web/flutter_facebook_login_web.dart.lib.js:87:94)
    at logIn.next (<anonymous>)
    at http://localhost:60059/dart_sdk.js:37211:33
    at _RootZone.runUnary (http://localhost:60059/dart_sdk.js:37065:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:60059/dart_sdk.js:32049:29)
    at handleValueCallback (http://localhost:60059/dart_sdk.js:32596:49)
    at Function._propagateToListeners (http://localhost:60059/dart_sdk.js:32634:17)
    at _Future.new.[_completeWithValue] (http://localhost:60059/dart_sdk.js:32477:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60059/dart_sdk.js:32499:35)
    at Object._microtaskLoop (http://localhost:60059/dart_sdk.js:37326:13)
    at _startMicrotaskLoop (http://localhost:60059/dart_sdk.js:37332:13)
    at http://localhost:60059/dart_sdk.js:32851:9
```

**Comment by amitkhairnar44** [comment]
https://github.com/kfiross/flutter_facebook_login_web/blob/dca80166587b32028e02e1e5d93790828f2243cb/lib/flutter_facebook_login_web.dart#L13-L17

The issue is on the line 17.

**Comment by diegocodigoup** [comment]
Solução:
linha 76 do arquivo flutter_facebook_login_web.dart
Trocar de:  
FacebookLoginResult._(Map<String, dynamic> map)

Para:
FacebookLoginResult._(Map<dynamic, dynamic> map)

**Comment by diegocodigoup** [comment]
Solução:
linha 76 do arquivo flutter_facebook_login_web.dart
Trocar de:
FacebookLoginResult ._ (Map <String, dynamic> map)

Para:
 FacebookLoginResult._(Map<dynamic, dynamic> map)

**Comment by kfiross** [comment]
Thanks for the help, Merged done and package update will be soon

**Comment by sobhan15** [comment]
> Here's the error log when i tried to login using:
> 
> ```dart
> final FacebookLoginResult result = await facebookSignIn.logIn(['email']);
> ```
> 
> ```
> Error: Expected a value of type 'Map<String, dynamic>', but got one of type 'LinkedMap<dynamic, dynamic>'
>     at Object.throw_ [as throw] (http://localhost:60059/dart_sdk.js:4322:11)
>     at Object.castError (http://localhost:60059/dart_sdk.js:4293:15)
>     at Object.cast [as as] (http://localhost:60059/dart_sdk.js:4609:17)
>     at dart.LegacyType.new.as (http://localhost:60059/dart_sdk.js:6151:60)
>     at logIn (http://localhost:60059/packages/flutter_facebook_login_web/flutter_facebook_login_web.dart.lib.js:87:94)
>     at logIn.next (<anonymous>)
>     at http://localhost:60059/dart_sdk.js:37211:33
>     at _RootZone.runUnary (http://localhost:60059/dart_sdk.js:37065:58)
>     at _FutureListener.thenAwait.handleValue (http://localhost:60059/dart_sdk.js:32049:29)
>     at handleValueCallback (http://localhost:60059/dart_sdk.js:32596:49)
>     at Function._propagateToListeners (http://localhost:60059/dart_sdk.js:32634:17)
>     at _Future.new.[_completeWithValue] (http://localhost:60059/dart_sdk.js:32477:23)
>     at async._AsyncCallbackEntry.new.callback (http://localhost:60059/dart_sdk.js:32499:35)
>     at Object._microtaskLoop (http://localhost:60059/dart_sdk.js:37326:13)
>     at _startMicrotaskLoop (http://localhost:60059/dart_sdk.js:37332:13)
>     at http://localhost:60059/dart_sdk.js:32851:9
> ```

### **still i faced with this issue in the 0.2.1 version**

**Comment by kfiross** [comment]
Hi, sorry for the inconvenience. I'll try to solve the issue

**Comment by amitkhairnar44** [comment]
@sobhan15 Are you sure?
I'm not getting this issue anymore.

**Comment by sobhan15** [comment]
yes it is ,
I also run flutter clean but the problem was not solved.
![Screenshot (9)](https://user-images.githubusercontent.com/37668537/90139167-3c4c9300-dd8d-11ea-8643-1f23a54686ee.png)

**Comment by amitkhairnar44** [comment]
@kfiross Have you reverted the changes?

**Comment by kfiross** [comment]
My bad, fixed it now

**Comment by amitkhairnar44** [comment]
@sobhan15 You can use this till @kfiross fixes the issue
```yaml
flutter_facebook_login_web:
    git:
      url: git://github.com/amitkhairnar44/flutter_facebook_login_web.git
```
